server:
  port: 9527
spring:
  application:
    name: SafeCommunityNet

  datasource:
    url: jdbc:mysql://localhost:3306/SCN
    username: root
    password: luluking123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
